name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install -U sphinx sphinx_rtd_theme myst-parser recommonmark
      - name: Build Documentation
        run: |
          sphinx-build docs/source/ docs/build/
      # - name: Encrypt files
      #   shell: bash
      #   env:
      #     PASSWORD: ${{ secrets.MYPASSWORD }}
      #   run: |
      #     npm install -g staticrypt
      #     find . -type f -name "*.html" -exec staticrypt {} $PASSWORD --output {} \;
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/
          force_orphan: true
